// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// xlogx
double xlogx(double x);
RcppExport SEXP _doubletree_xlogx(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(xlogx(x));
    return rcpp_result_gen;
END_RCPP
}
// logsumexp
double logsumexp(arma::vec logv_arma);
RcppExport SEXP _doubletree_logsumexp(SEXP logv_armaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type logv_arma(logv_armaSEXP);
    rcpp_result_gen = Rcpp::wrap(logsumexp(logv_arma));
    return rcpp_result_gen;
END_RCPP
}
// logexpit_cpp
double logexpit_cpp(double x);
RcppExport SEXP _doubletree_logexpit_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logexpit_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// logsumexp_row
double logsumexp_row(arma::rowvec logv_arma);
RcppExport SEXP _doubletree_logsumexp_row(SEXP logv_armaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type logv_arma(logv_armaSEXP);
    rcpp_result_gen = Rcpp::wrap(logsumexp_row(logv_arma));
    return rcpp_result_gen;
END_RCPP
}
// mtv
arma::mat mtv(arma::mat mat, arma::vec v);
RcppExport SEXP _doubletree_mtv(SEXP matSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mat(matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(mtv(mat, v));
    return rcpp_result_gen;
END_RCPP
}
// get_moments_cpp_doubletree
List get_moments_cpp_doubletree(arma::vec prob1, arma::mat prob2, arma::cube mu_gamma, arma::cube sigma_gamma, arma::cube mu_alpha, arma::cube sigma_alpha, List anc1, List anc2, arma::vec cardanc1, arma::vec cardanc2);
RcppExport SEXP _doubletree_get_moments_cpp_doubletree(SEXP prob1SEXP, SEXP prob2SEXP, SEXP mu_gammaSEXP, SEXP sigma_gammaSEXP, SEXP mu_alphaSEXP, SEXP sigma_alphaSEXP, SEXP anc1SEXP, SEXP anc2SEXP, SEXP cardanc1SEXP, SEXP cardanc2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type prob1(prob1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prob2(prob2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mu_gamma(mu_gammaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sigma_gamma(sigma_gammaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mu_alpha(mu_alphaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sigma_alpha(sigma_alphaSEXP);
    Rcpp::traits::input_parameter< List >::type anc1(anc1SEXP);
    Rcpp::traits::input_parameter< List >::type anc2(anc2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cardanc1(cardanc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cardanc2(cardanc2SEXP);
    rcpp_result_gen = Rcpp::wrap(get_moments_cpp_doubletree(prob1, prob2, mu_gamma, sigma_gamma, mu_alpha, sigma_alpha, anc1, anc2, cardanc1, cardanc2));
    return rcpp_result_gen;
END_RCPP
}
// get_moments_cpp_eco_gamma_doubletree
List get_moments_cpp_eco_gamma_doubletree(arma::vec prob1, arma::cube mu_gamma, arma::cube sigma_gamma, arma::cube E_beta, arma::cube E_beta_sq, List anc1, arma::vec leaf_desc);
RcppExport SEXP _doubletree_get_moments_cpp_eco_gamma_doubletree(SEXP prob1SEXP, SEXP mu_gammaSEXP, SEXP sigma_gammaSEXP, SEXP E_betaSEXP, SEXP E_beta_sqSEXP, SEXP anc1SEXP, SEXP leaf_descSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type prob1(prob1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mu_gamma(mu_gammaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sigma_gamma(sigma_gammaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_beta(E_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_beta_sq(E_beta_sqSEXP);
    Rcpp::traits::input_parameter< List >::type anc1(anc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type leaf_desc(leaf_descSEXP);
    rcpp_result_gen = Rcpp::wrap(get_moments_cpp_eco_gamma_doubletree(prob1, mu_gamma, sigma_gamma, E_beta, E_beta_sq, anc1, leaf_desc));
    return rcpp_result_gen;
END_RCPP
}
// get_moments_cpp_eco_alpha_doubletree
List get_moments_cpp_eco_alpha_doubletree(arma::mat prob2, arma::cube mu_alpha, arma::cube sigma_alpha, arma::cube E_eta, arma::cube E_eta_sq, List anc2, arma::vec leaf_desc);
RcppExport SEXP _doubletree_get_moments_cpp_eco_alpha_doubletree(SEXP prob2SEXP, SEXP mu_alphaSEXP, SEXP sigma_alphaSEXP, SEXP E_etaSEXP, SEXP E_eta_sqSEXP, SEXP anc2SEXP, SEXP leaf_descSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type prob2(prob2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mu_alpha(mu_alphaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sigma_alpha(sigma_alphaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_eta(E_etaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_eta_sq(E_eta_sqSEXP);
    Rcpp::traits::input_parameter< List >::type anc2(anc2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type leaf_desc(leaf_descSEXP);
    rcpp_result_gen = Rcpp::wrap(get_moments_cpp_eco_alpha_doubletree(prob2, mu_alpha, sigma_alpha, E_eta, E_eta_sq, anc2, leaf_desc));
    return rcpp_result_gen;
END_RCPP
}
// F_doubletree
arma::cube F_doubletree(arma::cube psi, arma::cube g_psi, arma::cube phi, arma::cube g_phi, arma::mat X, List ind_obs_i, arma::mat rmat, arma::cube E_beta, arma::cube E_beta_sq, arma::cube E_eta, arma::cube E_eta_sq, arma::vec v1_lookup_NA_replaced, arma::vec v2_lookup);
RcppExport SEXP _doubletree_F_doubletree(SEXP psiSEXP, SEXP g_psiSEXP, SEXP phiSEXP, SEXP g_phiSEXP, SEXP XSEXP, SEXP ind_obs_iSEXP, SEXP rmatSEXP, SEXP E_betaSEXP, SEXP E_beta_sqSEXP, SEXP E_etaSEXP, SEXP E_eta_sqSEXP, SEXP v1_lookup_NA_replacedSEXP, SEXP v2_lookupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type g_psi(g_psiSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type g_phi(g_phiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type ind_obs_i(ind_obs_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rmat(rmatSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_beta(E_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_beta_sq(E_beta_sqSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_eta(E_etaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_eta_sq(E_eta_sqSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v1_lookup_NA_replaced(v1_lookup_NA_replacedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v2_lookup(v2_lookupSEXP);
    rcpp_result_gen = Rcpp::wrap(F_doubletree(psi, g_psi, phi, g_phi, X, ind_obs_i, rmat, E_beta, E_beta_sq, E_eta, E_eta_sq, v1_lookup_NA_replaced, v2_lookup));
    return rcpp_result_gen;
END_RCPP
}
// update_emat_with_F_doubletree
arma::mat update_emat_with_F_doubletree(arma::cube curr_F, arma::mat rmat, arma::mat digamma_emat, arma::vec v2_lookup);
RcppExport SEXP _doubletree_update_emat_with_F_doubletree(SEXP curr_FSEXP, SEXP rmatSEXP, SEXP digamma_ematSEXP, SEXP v2_lookupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type curr_F(curr_FSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rmat(rmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type digamma_emat(digamma_ematSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v2_lookup(v2_lookupSEXP);
    rcpp_result_gen = Rcpp::wrap(update_emat_with_F_doubletree(curr_F, rmat, digamma_emat, v2_lookup));
    return rcpp_result_gen;
END_RCPP
}
// update_rmat_with_F_doubletree
arma::mat update_rmat_with_F_doubletree(arma::cube curr_F, arma::mat emat);
RcppExport SEXP _doubletree_update_rmat_with_F_doubletree(SEXP curr_FSEXP, SEXP ematSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type curr_F(curr_FSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type emat(ematSEXP);
    rcpp_result_gen = Rcpp::wrap(update_rmat_with_F_doubletree(curr_F, emat));
    return rcpp_result_gen;
END_RCPP
}
// update_gamma_subid_doubletree
List update_gamma_subid_doubletree(int u, arma::cube g_psi, double tau_1_t_u, arma::cube E_beta, arma::mat E_zeta_u, arma::mat X_zeropad, arma::mat rmat, arma::mat emat, arma::vec h_pau, arma::vec leaf_desc);
RcppExport SEXP _doubletree_update_gamma_subid_doubletree(SEXP uSEXP, SEXP g_psiSEXP, SEXP tau_1_t_uSEXP, SEXP E_betaSEXP, SEXP E_zeta_uSEXP, SEXP X_zeropadSEXP, SEXP rmatSEXP, SEXP ematSEXP, SEXP h_pauSEXP, SEXP leaf_descSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type g_psi(g_psiSEXP);
    Rcpp::traits::input_parameter< double >::type tau_1_t_u(tau_1_t_uSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_beta(E_betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type E_zeta_u(E_zeta_uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_zeropad(X_zeropadSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rmat(rmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h_pau(h_pauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type leaf_desc(leaf_descSEXP);
    rcpp_result_gen = Rcpp::wrap(update_gamma_subid_doubletree(u, g_psi, tau_1_t_u, E_beta, E_zeta_u, X_zeropad, rmat, emat, h_pau, leaf_desc));
    return rcpp_result_gen;
END_RCPP
}
// update_alpha_subid_doubletree
List update_alpha_subid_doubletree(int u, int v1, arma::cube g_phi, double tau_2_t_u, arma::cube E_eta, arma::mat E_xi_u, arma::mat X, arma::mat rmat, arma::mat emat, arma::vec h_pau, arma::vec levels, arma::vec subject_ids, arma::vec v2_lookup);
RcppExport SEXP _doubletree_update_alpha_subid_doubletree(SEXP uSEXP, SEXP v1SEXP, SEXP g_phiSEXP, SEXP tau_2_t_uSEXP, SEXP E_etaSEXP, SEXP E_xi_uSEXP, SEXP XSEXP, SEXP rmatSEXP, SEXP ematSEXP, SEXP h_pauSEXP, SEXP levelsSEXP, SEXP subject_idsSEXP, SEXP v2_lookupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type g_phi(g_phiSEXP);
    Rcpp::traits::input_parameter< double >::type tau_2_t_u(tau_2_t_uSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_eta(E_etaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type E_xi_u(E_xi_uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rmat(rmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h_pau(h_pauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type subject_ids(subject_idsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v2_lookup(v2_lookupSEXP);
    rcpp_result_gen = Rcpp::wrap(update_alpha_subid_doubletree(u, v1, g_phi, tau_2_t_u, E_eta, E_xi_u, X, rmat, emat, h_pau, levels, subject_ids, v2_lookup));
    return rcpp_result_gen;
END_RCPP
}
// update_alpha_subid_doubletree0
List update_alpha_subid_doubletree0(int u, int v1, arma::cube g_phi, double tau_2_t_u, arma::cube E_eta, arma::mat E_xi_u, arma::mat X, arma::mat rmat, arma::mat emat, arma::vec h_pau, arma::vec levels, arma::vec subject_ids, arma::vec v2_lookup);
RcppExport SEXP _doubletree_update_alpha_subid_doubletree0(SEXP uSEXP, SEXP v1SEXP, SEXP g_phiSEXP, SEXP tau_2_t_uSEXP, SEXP E_etaSEXP, SEXP E_xi_uSEXP, SEXP XSEXP, SEXP rmatSEXP, SEXP ematSEXP, SEXP h_pauSEXP, SEXP levelsSEXP, SEXP subject_idsSEXP, SEXP v2_lookupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type g_phi(g_phiSEXP);
    Rcpp::traits::input_parameter< double >::type tau_2_t_u(tau_2_t_uSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type E_eta(E_etaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type E_xi_u(E_xi_uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rmat(rmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h_pau(h_pauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type subject_ids(subject_idsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v2_lookup(v2_lookupSEXP);
    rcpp_result_gen = Rcpp::wrap(update_alpha_subid_doubletree0(u, v1, g_phi, tau_2_t_u, E_eta, E_xi_u, X, rmat, emat, h_pau, levels, subject_ids, v2_lookup));
    return rcpp_result_gen;
END_RCPP
}
// get_line1_2_15_doubletree
List get_line1_2_15_doubletree(arma::cube F, arma::mat digamma_emat, arma::mat rmat, arma::mat emat, arma::vec v1_lookup_NA_replaced, arma::vec v2_lookup);
RcppExport SEXP _doubletree_get_line1_2_15_doubletree(SEXP FSEXP, SEXP digamma_ematSEXP, SEXP rmatSEXP, SEXP ematSEXP, SEXP v1_lookup_NA_replacedSEXP, SEXP v2_lookupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type F(FSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type digamma_emat(digamma_ematSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rmat(rmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v1_lookup_NA_replaced(v1_lookup_NA_replacedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v2_lookup(v2_lookupSEXP);
    rcpp_result_gen = Rcpp::wrap(get_line1_2_15_doubletree(F, digamma_emat, rmat, emat, v1_lookup_NA_replaced, v2_lookup));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_doubletree_xlogx", (DL_FUNC) &_doubletree_xlogx, 1},
    {"_doubletree_logsumexp", (DL_FUNC) &_doubletree_logsumexp, 1},
    {"_doubletree_logexpit_cpp", (DL_FUNC) &_doubletree_logexpit_cpp, 1},
    {"_doubletree_logsumexp_row", (DL_FUNC) &_doubletree_logsumexp_row, 1},
    {"_doubletree_mtv", (DL_FUNC) &_doubletree_mtv, 2},
    {"_doubletree_get_moments_cpp_doubletree", (DL_FUNC) &_doubletree_get_moments_cpp_doubletree, 10},
    {"_doubletree_get_moments_cpp_eco_gamma_doubletree", (DL_FUNC) &_doubletree_get_moments_cpp_eco_gamma_doubletree, 7},
    {"_doubletree_get_moments_cpp_eco_alpha_doubletree", (DL_FUNC) &_doubletree_get_moments_cpp_eco_alpha_doubletree, 7},
    {"_doubletree_F_doubletree", (DL_FUNC) &_doubletree_F_doubletree, 13},
    {"_doubletree_update_emat_with_F_doubletree", (DL_FUNC) &_doubletree_update_emat_with_F_doubletree, 4},
    {"_doubletree_update_rmat_with_F_doubletree", (DL_FUNC) &_doubletree_update_rmat_with_F_doubletree, 2},
    {"_doubletree_update_gamma_subid_doubletree", (DL_FUNC) &_doubletree_update_gamma_subid_doubletree, 10},
    {"_doubletree_update_alpha_subid_doubletree", (DL_FUNC) &_doubletree_update_alpha_subid_doubletree, 13},
    {"_doubletree_update_alpha_subid_doubletree0", (DL_FUNC) &_doubletree_update_alpha_subid_doubletree0, 13},
    {"_doubletree_get_line1_2_15_doubletree", (DL_FUNC) &_doubletree_get_line1_2_15_doubletree, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_doubletree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
